### ISSUE TITLE
move survey.md to a github webpage

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#136]
We had the feeling that survey.md should not be a "paper paper" for a long time, and that a living document would be a better fit, to collect resources WITH the community. therefore a github project for a github page could be a better fit. For now we try to get sth. within the de-RSE society namespace https://github.com/DE-RSE .

**Comment by knarrff** [comment]
Should be possible - did not have time for this yet.

**Comment by CaptainSifff** [comment]
@knarrff @jlinx Any news here?

**Comment by CaptainSifff** [comment]
Tada!
We have the github URL:
https://github.com/DE-RSE/survey_rse_training
