### ISSUE TITLE
Organise deRSE24 workshop

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#215]
Hi all,
I handed in a talk and a workshop for our project. We should figure out a topic, slightly more concrete, than 
TeachingRSE - working Meeting.

**Comment by CaptainSifff** [comment]
My current estimate is that we get a 1hour workshop on Wednesday morning.

**Comment by CaptainSifff** [comment]
I think it would be worthwhile to focus on the institutions thing here.

**Comment by CaptainSifff** [comment]
- Format of the education.
- Ask audience on certification topics
- Imagine you can do it freely.
- Are RSEs different from Software Engineers?

**Comment by CaptainSifff** [comment]
So, after today's meeting we have decided on the following topic/question domains:

- 1a: Challenges/Lessons learned of Teachers currently teaching RSE things
- 1b: Who tries to incorporate RSE topics in their teaching?
- 2: Collect strategies of getting RSE topics into official university structures
- 3: Benefits of having dedicated RSE masters: Intention: convince others.
- 4: ask people of their opinion, what a beginning RSE should learn at the start of their career.
- 5: What are our teachers made of, and how can we find them
- 6: Work on the paper.

**Comment by CaptainSifff** [comment]
Assuming a 90mins slot (which we currently have) We would have the following split:
- 10 mins Intro
- 20 mins work-shift 1
- 20 mins workshift 2
- 15 mins workshift 3
- 15 mins workshift 4
- 10 mins Warp-Up.

**Comment by jcohen02** [comment]
@CaptainSifff I think it was mentioned that we wanted a couple of people per topic? I'd be happy to help @jpthiele with #228. Is the current title of this issue referring to RSE leaders? Maybe we could adjust it to something like: "_Benefits of having dedicated RSE leaders: Intention: Advocate, build recognition, convince others._"

**Comment by guadabsb15** [comment]
@CaptainSifff @jngrad if still needed I would be happy to help during the workshop with #229

**Comment by ljgarcia** [comment]
> Assuming a 90mins slot (which we currently have) We would have the following split:
> 
> * 10 mins Intro
> * 20 mins work-shift 1
> * 20 mins workshift 2
> * 15 mins workshift 3
> * 15 mins workshift 4
> * 10 mins Warp-Up.

I understood that we would have at least one moderator per table, is this correct? Will those moderators present some summary during the wrap-up? If yes, not sure 2.5 minutes per moderator is enough. We would go for 17 minutes per round and 12 for wrap-up.

**Comment by braunms** [comment]
I am also happy to help out with one of the rounds...

**Comment by CaptainSifff** [comment]
@braunms , @ljgarcia , @guadabsb15 Great you want to help, If you want to help organising,
have a look at the respective sub-issues and self-assign yourself to it. Currently the people repsonsible for the tasks, are more like caring for the issue until someone else takes over.

**Comment by CaptainSifff** [comment]
Assuming I made no mistake I rescheduled the workshop to: Thursday 09:00 - 10:30

**Comment by jngrad** [comment]
> Assuming I made no mistake I rescheduled the workshop to: Thursday 09:00 - 10:30

Thank you! I have to leave on Thursday at 14:00 and could not have attended the workshop a the time slot that appeared in the time table two days ago. I was probably careless and confused it with the similarly named block on Tuesday.

**Comment by jpthiele** [comment]
Alternative idea for the timings to make it more consistent and easier to digest:
10 minutes intro
2 x 15 minutes working
5 minute break
2 x 15 minutes working
15 minutes wrap up

**Comment by jcohen02** [comment]
> Alternative idea for the timings to make it more consistent and easier to digest:
>    10 minutes intro 
>    2 x 15 minutes working
>    5 minute break
>    2 x 15 minutes working
>    15 minutes wrap up

Just a quick note that the reasoning behind this is that it would probably be nice to wrap up the session with some sort of reporting back from the groups - if the reporting back is done by one of the moderators from each group, we can ensure that they stick to, say, 2 minutes each and with 15 minutes for wrapping up, that will ensure that we also have time to say a few words to close the workshop and say something about next steps.

**Comment by CaptainSifff** [comment]
We now have a session pad:
https://pad.gwdg.de/dHm6gU4HRu6zg7E57zY9SQ#

**Comment by CaptainSifff** [comment]
the conference has passed, and our pad has some feedback!
