### ISSUE TITLE
deRSE position-paper

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#218]
So from the deRSE societies website, this is the recipe we have to follow:

> Der Entwicklungsprozess für die Positionen der Gesellschaft wurde durch die Mitglieder gestaltet und kann bei Bedarf durch die Mitglieder verändert werden. Er verläuft in drei Phasen, die wie folgt gestaltet sind.
> 1. Aufruf- und Arbeitsphase
> 
>     Call for Collaboration: Initiatorinnen und Initiatoren einer Position kündigen das Thema auf der Mailingliste der Gesellschaft (liste@de-rse.org, mit Thema [Call for Contribution]) an und rufen die Mitglieder zur Mitarbeit auf. Dabei werden Hauptautorinnen und -autoren des Positionstextes benannt und die Bedingungen für Mitautorschaft erläutert.
>     Zusammenarbeit: Zusammenarbeit beginnt auf einer bevorzugt öffentlichen Plattform nach Wahl der Initiatorinnen und Initiatoren (*Pad, Repository, hackmd.io, Overleaf, o.ä.). Das Projekt wird gleichzeitig vorgestellt und verlinkt auf der de-rse.org Website unter [“Positionen” > “Work in progress”](https://www.de-rse.org/de/positions.html#work-in-progress) (per Pull Request gegen die Positionen-Seiten (de/en) auf https://github.com/DE-RSE/de-rse.github.io).
> 
> 2. Begutachtungsphase
> 
>     Veröffentlichung: Nach Fertigstellung eines zur Veröffentlichung vorgeschlagenen Entwurfs wird dieser zur Begutachtung freigegeben:
>         Soll die Position auf der de-RSE-Website unter “Positionen” veröffentlicht werden, wird ein entsprechender Pull Request (PR) gegen https://github.com/DE-RSE/positions/ gestellt (Entwurfsdateien in einem dedizierten Unterordner).
>         Ist eine andere Veröffentlichungsform vorgesehen, wird ein entsprechendes Issue auf https://github.com/DE-RSE/projekte eröffnet, das einen Link zum Entwurf enthält.
>     Call for Reviews: Die Entwurfsveröffentlichung wird wiederum über die Mailingliste (liste@de-rse.org, mit Thema [Call for Reviews]) bekanntgegeben, mit Link zum Pull Request/Issue. Die Mitgliedschaft wird zur Begutachtung bis zu einem geeigneten Termin aufgerufen.
>     Begutachtung: Die Mitgliedschaft begutachtet öffentlich den Entwurf im PR/Issue. Sollte der Entwurf eine kontroverse Diskussion initiieren, ist der PR/Issue mit einem Label [Kontroverse] zu markieren. Kontroverse Diskussionen/Gutachten sind solche, die in einem Peer-Review-Verfahren zu einer ablehnenden Entscheidung oder eine “Major revision” führen würden.
> 
> 3. Entscheidungsphase
> 
>     Entscheidung: Der Vorstand entscheidet, ob die vertretenen Positionen als “offizielle” Position von de-RSE e.V. - Gesellschaft für Forschungssoftware eingestuft werden:
>         Bei Diskussionen, die nicht als kontrovers gekennzeichnet wurden, wird die Entscheidung von mindestens einem Vorstandsmitglied getroffen.
>         Bei kontroversen Diskussionen/Gutachten entscheidet der Vorstand in einer Vorstandssitzung nach Möglichkeit im Konsens. Kann eine Einigung nicht gefunden werden, entscheidet der Vorstand mit einfacher Mehrheit.
>     Umsetzung: Eine Freigabe zur Veröffentlichung als Position des de-RSE e.V. wird umgesetzt entweder als Mergen und Schließen des entsprechenden Pull Request und Veröffentlichung der Position auf der Website, oder als Imprimatur-Kommentar (“Freigabe”) und Schließen des entsprechenden Issue. Erfolgt keine Freigabe, kann der Vorstand den Entwurf zur Überarbeitung zurück an die Autorenschaft geben, dies wird im entsprechenden Issue/PR per Kommentar vermerkt. Hierbei sind Hinweise zu benötigten Änderungen zu geben. Alternativ kann der Vorstand den Entwurf ablehnen. Hierbei werden Issue/PR mit entsprechendem Kommentar geschlossen und es erfolgt keine Veröffentlichung.

**Comment by CaptainSifff** [comment]
We now have a draft PR https://github.com/DE-RSE/positions/pull/15
It's not super-urgent, but to get it started seriously...
pinging
@knarrff , @jlinx , @MakisH , @jcohen02 , @jngrad

**Comment by CaptainSifff** [comment]
Out!

**Comment by CaptainSifff** [comment]
So, if we have sorted out the remaining PRs, it would be time to open the review phase.

**Comment by CaptainSifff** [comment]
Mail is out,
current schedule is:
The Deadline for contributions is:

**   14.02.24  **

After that, the review phase for the community will start.
Intended end of our review phase will be on

** 29.02.24  **

With the aim of wrapping up for deRSE24.

**Comment by CaptainSifff** [comment]
Which could mean, that our meeting on the 16.02.24 will be a big one....

**Comment by knarrff** [comment]
That PR needs to be refreshed, at which point we can go from step 1 to step 2

**Comment by CaptainSifff** [comment]
update arxiv version.

**Comment by CaptainSifff** [comment]
call for review is out!

**Comment by CaptainSifff** [comment]
the deadline for review is currently 09.08.  23:59 and we are now scheduling a second meeting this friday.

**Comment by CaptainSifff** [comment]
@knarrff  The upload to a PR has happend:
https://github.com/DE-RSE/positions/pull/15

**Comment by CaptainSifff** [comment]
Closing this, as we did it!
