### ISSUE TITLE
New RSE specialization: Open Source Developer

### ISSUE THREAD

**Issue by Bisaloo** [the-teachingRSE-project/competencies#25]
Open source developer RSEs work on large pieces of software relevant for the wider research community. Oftentimes, it will be general purpose statistical or data analysis library, such as [Stan](https://mc-stan.org/about/team/) or [SciPy](https://scipy.org/teams/).

They are probably closer to industry roles than other RSE specializations currently in the paper but I still believe it makes sense to consider them as RSEs because:
- they need to understand the research lifecycle to inform the software lifecycle and their processes regarding breaking changes, new features rollout, etc.
- they need to be able to communicate efficiently with researchers who are the majority of their userbase and contribute most bug reports & feature requests
- it's more common for them to have a research background (or even to currently be affiliated to a research structure) than on average in industry

The name may sound similar to Open Science RSE but I believe they are very different: the Open Science RSE will mostly focus on making research artifacts open & FAIR, while the Open Source Developer RSE will play a role earlier in the research process, by providing low-level libraries used to produce these research artifacts.
In some way, the closest specialization is probably the Web-Development RSE but they focus on very different product and use very different languages & frameworks.

**Comment by mschwarzmeier** [comment]
Hi,
discussion seems a bit cooled down. 
Anyways... my take on this is the OpenScience-RSE, as currently described in the master version seems to be more of a domain RSE, that works in an open project. Therefore artifacts might be simulation data (and similar) and to make things reproducible a container or "reproducibility" with scripts.
An OpenSource-Dev-RSE will have no (or little) simulation output but his/her artifacts will be the software as packages, like those packages Bisaloo gave. E.g. interoperability, speed, efficiency is much more important than for a domain RSE. Exaggerated: OSource-Developer-RSE run unit tests, OpenScience-RSEs run simulations.
I see overlap with the HPC-RSE, but not so focused on hardware and administration, legal, environmental, scheduling and proposals.

**Comment by knarrff** [comment]
I think this is now covered with a combination of "open science RSE" and "project/community manager RSE".

**Comment by knarrff** [comment]
(don't hesitate to re-open - I am just in the process of cleaning up a little)
