### ISSUE TITLE
Unknown unknowns from SE

### ISSUE THREAD

**Issue by jpthiele** [the-teachingRSE-project/competencies#263]
This is a collection of topics that came up at Dagstuhl that we were not aware of previously.
We also discussed whether they are something that RSE students should be skilled in 
or only be aware of in general.
We'll have to think about how to integrate some of those somewhere.
Some are separate issues already.

Skills:
- Adaptability & continued learning (rewording of curiosity)
- Using and understanding code analysis tools

In between:
- Software Modeling (e.g. UML and it's subtypes)

Awareness:
- Ethics in research life cycle
- Variant Management & Product line management 
- Further aspects of automation, frameworks and testing.

**Comment by jpthiele** [comment]
Code analysis tools should fit in MOD but we might specify more.

**Comment by CaptainSifff** [comment]
anything more to add here? Or can we close this?
