### ISSUE TITLE
Suggested title change

### ISSUE THREAD

**Issue by annalenalamprecht** [the-teachingRSE-project/competencies#265]
In the discussions at Dagstuhl it also turned out that several people are having issues with the "foundational" qualification of the competencies in the title. 

Suggested change: "Identifying Competencies and Responsibilities of a Research Software Engineer". 

This version just does not qualify if the competencies in the paper are foundational, basic, complete, whatsover (as people really cannot agree on this), and also emphasizes that this is an ongoing discussion.

**Comment by hvwaldow** [comment]
In my mind we are aiming at providing exactly that: Foundational aka basic competencies. "Complete" is something different. This paper is presenting competencies that we have identified. It's not about "identifying".

**Comment by annalenalamprecht** [comment]
How about "Identified Competencies and Responsibilities of a Research Software Engineer" then?

**Comment by CaptainSifff** [comment]
#276 has now qualified a bit of what we mean. Do you feel it is resolved?

**Comment by rumpe** [comment]
There was a good suggestion to distinguish between "Research Softare Engineers" and "Scientists Who Code".

My argument would be that the paper is very good for scientists who code, but it ignores all the competencies that a software engineer (and thus an automotive software engineer, an avionik software engineer or a research software engineer) should have.

Suggested change: "Identifying Foundations Competencies and Responsibilities of a `Scientist who Codes`".
and clarifying this term in the paper as well.
(or adding all the competencies that a software engineer should have to the paper).

**Comment by juckel** [comment]
I propose to solve this with adding a subtitle to the paper (maybe after a "--"): "From scientists who code to full-time software engineers"

My rationale:
I agree with both @mhagdorn and @rumpe. On the one hand some of the competencies we list for an RSE are more on the scientist-who-codes side of the spectrum, thus also diluting the term SE a bit. As Bernhard mentioned this might also make the bridge building between the two communities that we currently work on more difficult, as our paper with its current title also makes a potential funding politics statement/claim. On the other hand I also see that we need to promote the term RSE and show that it actually has the same breadth as (enterprise) software developers, who also work on codes from small prototypes to large enterprise/infrastructure software. At the same time the "research" part of RSE also adds a dimension that is not (always) present in the more traditional SE.

**Comment by michelemartone** [comment]
> There was a good suggestion to distinguish between "Research Softare Engineers" and "Scientists Who Code".
> 
> My argument would be that the paper is very good for scientists who code, but it ignores all the competencies that a software engineer (and thus an automotive software engineer, an avionik software engineer or a research software engineer) should have.
> 
> Suggested change: "Identifying Foundations Competencies and Responsibilities of a `Scientist who Codes`". and clarifying this term in the paper as well. (or adding all the competencies that a software engineer should have to the paper).

@rumpe , this paper is to delineate competencies to create a breed of specialists with skills that "Scientists Who Code" have and which "Software Engineers" have. Think of "Econometrics" or "Mechatronic Engineering".
In other words, the use of "Research Software Engineer" is meant to churn out specialists which are with one foot in each of the two boats.

Given this, is it so that you would prefer the entire community to be instead named "Scientists who code well" or something with that meaning ?

**Comment by annalenalamprecht** [comment]
> I propose to solve this with adding a subtitle to the paper (maybe after a "--"): "From scientists who code to full-time software engineers"
> 

Thank you for this suggestion, @juckel ! I think it's the best so far. ;)
It would however mean that the paper would also (seriously) need to include software engineering skills and competencies, as @rumpe remarked earlier.

**Comment by hvwaldow** [comment]
The meaning of "RSE" doesn't have a clear, unambiguous, consensual definition yet. That is a symptom of the problem that RSE societies want to address. My understanding from what the community perceives as "RSE" is that not all "scientists who code" are RSEs, but a lot of RSE are, in fact, scientists who code. "RSE" in the current context does not imply a certain skill-level or breadth of SE-related skills. Here we want to contribute to change that and I believe @rumpe is absolutely right to expect that core SE-skills are an essential part of an ideal RSE's skill-set.
  
I would like to read his comment as a hint that we did a not so good job at communicating that indeed,

 > The technical skills required by an RSE overlap to a large extent with the common fundamental software engineering skills (see, e.g., @Landwehr2017), ...

We do mention requirements engineering, design, implementation, testing & validation, documentation, maintenance. Not sure what essential SE-skills relevant for RSEs are missing here. But in any case, we could communicate the essential nature of general SE competencies more prominently and better reference standard SE textbooks, curricula,  SWEBOK, ...

**Comment by annalenalamprecht** [comment]
> In the [EVERSE](https://everse.software) project I worked hard to replace "best practice" with "good enough practice". I also believe that this is the case for this paper. We don't expect an RSE to be outstanding in all competencies we list, but rather be aware that all these make up the breadth of what an RSE can do. And then, as needed, one advances his/her/their skill set using our paper as one potential guideline.

Very much reminds me of Wilson et al.'a "Best Practices in Scientific Computing" (2014, [https://doi.org/10.1371/journal.pbio.1001745](https://doi.org/10.1371/journal.pbio.1001745)) that was some years later replaced by "Good Enough Practices in Scientific Computing" (2017, [https://doi.org/10.1371/journal.pcbi.1005510](https://doi.org/10.1371/journal.pcbi.1005510)), arguably also realizing that the first as not a good fit for the target group. 

The different interpretations of what an RSE is seem to add to the complication in our case, though.

**Comment by annalenalamprecht** [comment]
As for EVERSE, it's admittedly ironic if a project on "research software excellence" promotes "good enough" practices. ;)

**Comment by mhagdorn** [comment]
I also like the subtitle idea of @juckel. I am slightly concerned however, that it could be read as how to progress from scientist who codes to full-time SE rather than being inclusive.

**Comment by BeastyBlacksmith** [comment]
> > I propose to solve this with adding a subtitle to the paper (maybe after a "--"): "From scientists who code to full-time software engineers"
> 
> Thank you for this suggestion, @juckel ! I think it's the best so far. ;) It would however mean that the paper would also (seriously) need to include software engineering skills and competencies, as @rumpe remarked earlier.

Can you be more specific which software engineering skills and competencies you would like to see included?

**Comment by jlinx** [comment]
> I also like the subtitle idea of @juckel. I am slightly concerned however, that it could be read as how to progress from scientist who codes to full-time SE rather than being inclusive.

I agree with @mhagdorn that this very subtitle could make the impression even worse. Because IMHO the paper does NOT address how to proceed towards more software engineering.  However, I like the idea of @juckel to add a subtitle in general, too.

**Comment by annalenalamprecht** [comment]
> Can you be more specific which software engineering skills and competencies you would like to see included?

@BeastyBlacksmith It's not that there are no SE skills and competencies included yet. But the reference to the SWEBOK and related works is at the moment something like a single sentence that is hard to overlook, and other "classical" SE skills are mixed with the RSE skills identified and presented in the paper. Somehow the paper needs to acknowledge more visibly/prominently that there IS already a large set of established SE practices that of course also matter here. Perhaps by not only mentioning SWEBOK, but devoting a section to it to describe what it includes. Other ideas welcome!

**Comment by fer-rum** [comment]
Then maybe a variation for the subtitle:

_About scientists who code and full-time software engineers_

**Comment by mhagdorn** [comment]
what about

_Foundational Competencies and Responsibilities of a Research Software Engineer - for both scientists who code and software engineers in research_

although we don't want to restrict the readership to just RSEs

**Comment by hvwaldow** [comment]
> what about
> 
> _Foundational Competencies and Responsibilities of a Research Software Engineer - for both scientists who code and software engineers in research_
> 
> although we don't want to restrict the readership to just RSEs

_Foundational Competencies and Responsibilities of a Research Software Engineer - for both scientists who develop software and software engineers supporting scientists_

**Comment by mhagdorn** [comment]
> _Foundational Competencies and Responsibilities of a Research Software Engineer - for both scientists who develop software and software engineers supporting scientists_

cool, I like that. This seems to be an iterative process

**Comment by rumpe** [comment]
May I potentially add the following issue: I find the wikipedia definition of RSE (https://en.wikipedia.org/wiki/Research_software_engineering) quite agreeable and very intuitive:

"Research software engineering is the use of [software engineering](https://en.wikipedia.org/wiki/Software_engineering) practices, methods and techniques for research software, ...."

As a software engineer, I have to say that: When I look at that paper, the paper does NOT talk about the core competencies of a software engineer at all. So I find the paper title as it is does not fit to the paper content.

BTW: TU Munich is placing a bust for the German founders of software engineering, F.L. Bauer, on Montay 10th at the TU Munich, because he would have 100th birthday. (While the software engineering field is only ~60 years old.)

**Comment by rumpe** [comment]
May I potentially add the following issue: I find the wikipedia definition of RSE (https://en.wikipedia.org/wiki/Research_software_engineering) quite agreeable and very intuitive:

"Research software engineering is the use of [software engineering](https://en.wikipedia.org/wiki/Software_engineering) practices, methods and techniques for research software, ...."

As a software engineer, I have to say that: When I look at that paper, the paper does NOT talk about the core competencies of a software engineer at all. So I find the paper title as it is does not fit to the paper content.

BTW: TU Munich is placing a bust for the German founders of software engineering, F.L. Bauer, on Montay 10th at the TU Munich, because he would have 100th birthday. (While the software engineering field is only ~60 years old.)

**Comment by rumpe** [comment]
And this is why I would suggest you either change the title or add the core competencies of a software engineer to the body of the paper.

At least I would not be confronted with a paper that tells me that the list of core compentencies of a research software engineer does roughly not contain any content of the software engineering field (except version control).

**Comment by hvwaldow** [comment]
How about something like that?

https://github.com/the-teachingRSE-project/competencies/blob/1cba3c793cd8d682215a507efe0995ddbc6e2825/competencies.md?plain=1#L473-L496

**Comment by rumpe** [comment]
I had a loook at the core principles that a software engineer should know.
Actually the Software Engineering Body of Knowledge, the FAIR principles are not included there.

I would also like to add that some of the misunderstandings we have here come from the view that something like "traditional software development life cycle " still exists.
(that was in the 70ties and 80ties). Since then SE has slightly enhanced its body of core competencies.

**Comment by rumpe** [comment]
These are to my belief correctly core competencies: "Proper requirement elicitation, analysis and specification are of the essence for any successful development project. " But only mentioning them makes the paper somehow ill balanced compared to other competencies. 
However, it comes iinto the right directions ...

**Comment by knarrff** [comment]
Where do we meet? It does not seem to be the regular zoom room.

**Comment by CaptainSifff** [comment]
One thing at least I'd like to rememember from today's discussion is that currently ~60% of the content of our paper is not mentioned in our title....

**Comment by CaptainSifff** [comment]
a new idea: Foundational Competencies and Responsibilities of a (Research Software) Engineer?

**Comment by MakisH** [comment]
Looking at the whole discussion a bit late (I was offline over the past two weeks), maybe some of these (summarizing) points help:

I think the unique skills of an RSE is that they have knowledge both of Research and of Software Engineering. The additional complexity comes from this two-dimensional field (@CaptainSifff @knarrff @mhagdorn). As "mechatronics" is a specialization that requires both Mechanical Engineering and Electronics knowledge, so is RSE a hybrid specialization (@jpthiele).

For this reason (and to emphasize the relevance to the RSE-related literature), I think we should keep the `Research Software Engineer` in the title.

The braces in the title would add more confusion, in my view. But we can introduce this distinction in one of the sections.

I find the discussion very interesting and useful, and I understand that we need to add a section about the "usual" Software Engineering skills that an RSE should also know. This would also improve the structure and bring symmetry with Research, as we already have the `Ability to do Research` (previously: `Curiosity`) as a skill.

**Comment by hvwaldow** [comment]
> a new idea: Foundational Competencies and Responsibilities of a (Research Software) Engineer?

That would be very confusing. People don't expect parentheses to clarify the intended associativity of Nouns in a title.

**Comment by hvwaldow** [comment]
> * 4.1.2 Adapting to the software life cycle

Yes, like that. Except its unclear what 4.1.2 should contain then. Also the other 4.1.x section cover content that is part of the standard SE curriculum. Maybe settle first on the list of "technical  aspects of Software Engineering". I guess that would be requ. engineering, design, sw construction, testing.

**Comment by knarrff** [comment]
Will be resolved with #290
