### ISSUE TITLE
Critical thinking with machines.

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#266]
the discussion on UML led to th erealization that critically questioning the output of any machine generated artifact(e.g. by an ML system) is a core RSE skill.

**Comment by CaptainSifff** [comment]
Probably in the area between 3 and 3.1

**Comment by mhagdorn** [comment]
I wrote a few sentences on critical engagement with tools. I feel well out of my depth here. So please feel free to chip in.

**Comment by jpthiele** [comment]
This somehow also comes back in part to V&V (verification and validation) 
and questioning yourself on whether you put everything together correctly is one of the two.

**Comment by CaptainSifff** [comment]
now followed by #283
