### ISSUE TITLE
Add responsibility of employer to (NEW) 

### ISSUE THREAD

**Issue by jpthiele** [the-teachingRSE-project/competencies#274]
After reading it again I agree even more with @tobyhodges 
in that we should rephrase the text some.
Because lifelong learning pins somehow pins all responsibility on the individual.
We should make clear that even with a high skill level learning new things 
will need time and that this time should be given if the skill is relevant to the work.

**Comment by CaptainSifff** [comment]
Making institutions for that available would be part of the next in this series.
But good point!

**Comment by jpthiele** [comment]
Even without institutions, getting the time during your work day to follow a tutorial on something is a need.
