### ISSUE TITLE
Paper Reference: "RSMM: A Framework to Assess Maturity of Research Software Project"

### ISSUE THREAD

**Issue by fer-rum** [the-teachingRSE-project/competencies#284]
Hi everyone,
I just came across this quite recent preprint and found it pretty interesting as it covers a few of the topic that this paper also touches on. Maybe it is wort checking out / referencing?

* :memo: RSMM: A Framework to Assess Maturity of Research Software Project
* :busts_in_silhouette: [Deekshitha](https://arxiv.org/search/cs?searchtype=author&query=Deekshitha), [Rena Bakhshi](https://arxiv.org/search/cs?searchtype=author&query=Bakhshi,+R), [Jason Maassen](https://arxiv.org/search/cs?searchtype=author&query=Maassen,+J), [Carlos Martinez Ortiz](https://arxiv.org/search/cs?searchtype=author&query=Ortiz,+C+M), [Rob van Nieuwpoort](https://arxiv.org/search/cs?searchtype=author&query=van+Nieuwpoort,+R), [Slinger Jansen](https://arxiv.org/search/cs?searchtype=author&query=Jansen,+S)
* :link: https://arxiv.org/abs/2406.01788

> The organizations and researchers producing research software face a common problem of making their software sustainable beyond funding provided by a single research project. This is addressed by research software engineers through building communities around their software, providing appropriate licensing, creating reliable and reproducible research software, making it sustainable and impactful, promoting, and ensuring that the research software is easy to adopt in research workflows, etc. As a result, numerous practices and guidelines exist to enhance research software quality, reusability, and sustainability. However, there is a lack of a unified framework to systematically integrate these practices and help organizations and research software developers refine their development and management processes. Our paper aims at bridging this gap by introducing a novel framework: RSMM. It is designed through systematic literature review and insights from interviews with research software project experts. In short, RSMM offers a structured pathway for evaluating and refining research software project management by categorizing 79 best practices into 17 capabilities across 4 focus areas. From assessing code quality and security to measuring impact, sustainability, and reproducibility, the model provides a complete evaluation of a research software project maturity. With RSMM, individuals as well as organizations involved in research software development gain a systematic approach to tackling various research software engineering challenges. By utilizing RSMM as a comprehensive checklist, organizations can systematically evaluate and refine their project management practices and organizational structure.

**Comment by CaptainSifff** [comment]
Thank you for that idea! that should be interesting for @jngrad . Do you have an idea where it would fit into?

**Comment by MakisH** [comment]
Maybe interesting in the context of #35?
