### ISSUE TITLE
Add a paragraph to the introduction explaining the discussion of (RS)E vs. R(SE)

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#287]
So, in the title it says paragraph, but the idea, of making the title 
"Foundational competencies of an (RS)E" also belongs here.

Content of this paragraph could be
- the discussion of where to put the brace
- emphasizing that it's not just the technical complexity that we handle, but also the research and social complexity. Thereby covering a larger complexity than an engineer.
-  the discussion, that different RSE societies put the emphasis slightly different in that spectrum.
- start out with Venn diagrams

**Comment by CaptainSifff** [comment]
RSE: schnittstellenwissenschaft: Interface Discipline

**Comment by hvwaldow** [comment]
We can cite Anna-Lena in GI-Radar.
https://gi-radar.de/351-research-software/
