### ISSUE TITLE
Work out the engineering aspect

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#289]
Work out the engineering aspect.
A bit in the direction of #288, and #287  but instead of focusing on the SE aspects, work out a bit the traditional engineering
aspect. Thereby we put the emphasis more on (RS)E , thereby applying engineering practices towards Research Software.
In this item, I would really drive more towards changes in the skill section that concentrate on traditional engineering: create reliable products for humans. Not necessarily restricted to SE. It also ties in nicely with the FAIR discussion, and separates the RSE from any digitalization things in the domain sciences.

**Comment by CaptainSifff** [comment]
In my attempt to fugure out what engineering is, I came to this:

> While the initial discussion focused on software engineering, many of the principles are indeed applicable across various engineering disciplines. Here are some key attributes that generally constitute a well-engineered product across all engineering fields:
> Reliability: The product consistently performs its intended functions without failures over time. This applies to mechanical, electrical, and software components alike.
> Efficiency: The product makes optimal use of resources, whether it's energy, materials, or processing power.
> Maintainability: The product is designed to be easily repaired, updated, or modified as needed. This is crucial for all types of engineered products, from software to machinery.
> Usability: The product is user-friendly and intuitive to operate, regardless of whether it's a physical device or a software application.
> Safety: The product is designed to be safe for users and the environment, a critical consideration in all engineering disciplines.
> Quality Assurance: Rigorous testing and validation procedures are implemented throughout the development process.
> Documentation: Comprehensive documentation is provided, covering all aspects from requirements to final acceptance testing.
> Functional Performance: There is a strong focus on how the product operates and performs its intended functions.
> Requirements Management: Detailed requirements are tracked and managed throughout the development process.
> Collaborative Development: Custom-engineered products often require close collaboration between various teams, including sales, engineering, purchasing, operations, and finance.
> Product Instincts: Engineers develop strong product instincts through repeated cycles of learning, which applies to all disciplines.
> Business and User Understanding: Engineers across all fields benefit from understanding the business context and user needs of their products.
> These attributes are generally applicable across mechanical, electrical, civil, chemical, and other engineering disciplines, not just software engineering. The specific implementation may vary, but the underlying principles of what constitutes a well-engineered product remain consistent across fields.

**Comment by jpthiele** [comment]
And the main thing that sets SE apart from traditional engineering disciplines 
is the broad understanding of natural sciences and laws on which all physical products are based.

**Comment by jcohen02** [comment]
> In my attempt to fugure out what engineering is, I came to this:

This list is great. Maybe something else to add (which somewhat ties together a group of the other items, so maybe it doesn't need to be represented separately):

Sustainability: The product is designed with a view to supporting long maintenance, potentially by people other than the original designers/engineers, in order to address changing or developing requirements over time.

**Comment by CaptainSifff** [comment]
with regard to the science thing: My intent is to have sth. that doesn't go too much into the science corner...

**Comment by CaptainSifff** [comment]
if you want a meme, I found this: https://imgur.com/zjugQ8q
