### ISSUE TITLE
repo: delete old branches, especially from merged PRs

### ISSUE THREAD

**Issue by knarrff** [the-teachingRSE-project/competencies#311]

**Comment by knarrff** [comment]
One strange problem here is that these are ahead of main, even though the changes they requested are in main, but as new commits.

**Comment by jpthiele** [comment]
Yeah GitHub has a hard time figuring out that the merged commit with a different tag is the same as the commit on the branch... 
All merged branches are deleted now. 
For the draft and closed PRs I did not want to decide for anyone else, so there everyone should look at their own branches.
