### ISSUE TITLE
table 2 NEW/Senior RSE

### ISSUE THREAD

**Issue by mhagdorn** [the-teachingRSE-project/competencies#322]
Is the entry for NEW/Senior RSE Table 2 correct: I didn't think the NEW skill was about developing software

**Comment by MakisH** [comment]
Current state:

![Screenshot from 2024-07-31 23-45-37](https://github.com/user-attachments/assets/f70d6975-2951-44a8-bdc5-e3db847a33bc)

True, it is not about developing software. However, the intention here is to emphasize the proactivity.

Maybe:

```diff
- Same as junior, but they need to proactively change the code.
+ Same as junior, but they should proactively propose directions in individual aspects of the project.
```

**Comment by knarrff** [comment]
Sounds good to me: do you want to pull-request this?
