### ISSUE TITLE
Ensure consistent use of the term Research Software Engineering

### ISSUE THREAD

**Issue by jcohen02** [the-teachingRSE-project/competencies#334]
A minor point on consistency: "Research Software Engineering" (i.e. the expanded version of RSE) occurs a few times in the text.

We should ensure that we are consistent with capitalisation (or not) of this term - in some cases it's capitalised and other times it's not. I don't recall if this has previously been discussed and some convention for this is already in use?

**Comment by knarrff** [comment]
Should be handled now.
