### ISSUE TITLE
work in feedback from Yves Großmann

### ISSUE THREAD

**Issue by CaptainSifff** [the-teachingRSE-project/competencies#339]
We should work in the feedback from Yves Großmann:
https://github.com/yvgrossmann/rse-teaching-competencies

**Comment by CaptainSifff** [comment]
@jcohen02 , @jpthiele , @mhagdorn , @MakisH : My git skills give up by now....

I'd like to have some feedback on the changes that I brought about in this commit from the feedback by @yvgrossmann : 
https://github.com/the-teachingRSE-project/competencies/commit/76d9ff749f21950aae063524b39467a9bae217e9

**Comment by CaptainSifff** [comment]
Here's the ref, that we might want to consider: https://zenodo.org/records/10374839

**Comment by MakisH** [comment]
All points are already addressed by @jcohen02 in #347.

**Comment by knarrff** [comment]
As far as I can see, the fork here does not contain new commits.

**Comment by CaptainSifff** [comment]
there will be a second try of me vs. git ....
