### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jpthiele** [the-teachingRSE-project/competencies#356]
We noticed in the meeting that the titlepage and ToC need some fixing.

**Comment by jpthiele** [comment]
For the ToC we could use the following in the frontmatter

```
  - \usepackage{tocloft}
  - \setlength{\cftbeforesectionskip}{0.5\baselineskip}
```

although I'm not sure if `\baselineskip` is the correct size. 
Could not find it on the spot.

**Comment by CaptainSifff** [comment]
with these two items merged, we can close this.

**Comment by jpthiele** [comment]
Perfect!

**Comment by MakisH** [comment]
It's actually fine as-is. The Glossary could start on a new page, but that would make barely any difference in anything.
