### ISSUE TITLE
Further Condensation of Summary Paper

### ISSUE THREAD

**Issue by mhagdorn** [the-teachingRSE-project/competencies#368]
From the [author info page](https://www.computer.org/csdl/magazine/cs/write-for-us/14597?title=Author%20), we can have between 2,400 and 6,250 words, including all main body, abstract, keyword, bibliography (12 references or less), and biography text.  That's really not a lot.

* **Current challenges** - the section I have put back in: 343 words
* **RSE Specialisations**: 1421 words
* **Future Work**: 392 words
* Glossary, Skill Codes and Acronyms can probably go as well, depending on what we do with the Specialisations Section.
* That leaves shortening the Intro and the **Contribution details** sections

**Comment by MakisH** [comment]
If we want to not kick out complete sections, I can try summarizing the RSE Specialisations and Future Work. What do you think?

If yes, just give me a word limit, and I will stick to that.

> Glossary, Skill Codes and Acronyms can probably go as well, depending on what we do with the Specialisations Section.

Yes, I think it is totally fine to remove these in a shortened version.

> That leaves shortening the Intro and the Contribution details sections

Alternatively to the above, I can summarize the intro (but not both).

Do we need the Contribution details if we only have `The teachingRSE project` as author?

**Comment by MakisH** [comment]
Alright, I can prepare something for Monday.

**Comment by CaptainSifff** [comment]
For the specialisation, @knarrff , and @jpthiele offered to work on condensing the specializations.

**Comment by CaptainSifff** [comment]
If someone wants to reintroduce the tasks-and-responsibilites in a shortened variant, have a go!

**Comment by CaptainSifff** [comment]
the attached version generated by pdf2text is now at 7953 word according to wc.
[summarised_competencies.txt](https://github.com/user-attachments/files/17590615/summarised_competencies.txt)

**Comment by CaptainSifff** [comment]
with the work on the refs, I think we have to cut 1000 words more...

**Comment by mhagdorn** [comment]
I think this is done now
