### ISSUE TITLE
remove Skill codes in condensed version of paper

### ISSUE THREAD

**Issue by mhagdorn** [the-teachingRSE-project/competencies#381]
I think the Skill codes section does not make so much sense in the condensed version of the paper.  I reckon we can remove that too. 

Do we want to keep the icons for the condensed version?

**Comment by jpthiele** [comment]
I am not completely sure what you mean exactly.

**Comment by mhagdorn** [comment]
> I am not completely sure what you mean exactly.

At the end of the condensed paper we have the Sections Glossary, Skill codes and Acronyms. I think we should definitely remove the Glossary, it only has two items. I think we can also drop the Acronyms, just expand them inline (which I think we are already doing). The remaining one Skill codes I am not so sure about. I think in the condensed version of the paper it doesn't make as much sense as in the full paper. So, I tend to dropping that as well.

**Comment by jpthiele** [comment]
Ahh, I had that all filed under 'removed glossary' in my mind.
Yes I don't think we need the section in a shorter version of the paper,
while the hover is a nice feature I don't think too many people will notice that anyways.

**Comment by mhagdorn** [comment]
you are quite right, I didn't realise all three sections were controlled by the glossary. Removing all three was also easy, see PR #382
