### ISSUE TITLE
Porting the summarized competencies to the target template

### ISSUE THREAD

**Issue by MakisH** [the-teachingRSE-project/competencies#383]
When converting the paper to the target template, we should:

- [x] Remove the ORCiD from the author
- [x] Check how the glossary fits and works, potentially remove it
- ~~Mention Dagstuhl seminar in intro~~

**Comment by MakisH** [comment]
> did you mean we mention it in our intro?

@mhagdorn had the original suggestion to mention Dagstuhl in the intro.

I just added this here to remember to handle it, as I guess it depends on the information present in the template/context.

**Comment by mhagdorn** [comment]
template here https://www.overleaf.com/2737254243zdfjtwhnvpyx#29b77f

**Comment by CaptainSifff** [comment]
Deadline 15.12

**Comment by mhagdorn** [comment]
@MakisH @jpthiele I had a first go at filling the template, there are still a number of issues with our custom macros. they also want American English spelling ;-( The two of you can edit. What are we going to do with the author?

**Comment by MakisH** [comment]
> there are still a number of issues with our custom macros.

I fixed the errors and warnings (besides the usual underfull/overfull, which we should address last):

- Replaced all the `\gls` with expanded terms
- Replaced all the `\ac` with the acronyms as-is (in most cases, but occasionally expanded)
- Removed all the `\ref`, since the sections are not numbered

> they also want American English spelling ;-( 

Great! Finally! :smile: I fixed as much as I could catch with my spellchecker.

> What are we going to do with the author?

I thought we had decided on that as `The teachingRSE project`. I guess it depends on whether this is allowed.

**Comment by jpthiele** [comment]
Currently we cite both the arXiv and F1000 version which brings us to 13 references.
Additionally, all reference text will be counted for the overall word limit.
I suggest we only reference F1000?

**Comment by jpthiele** [comment]
But the good news!
I copied the paragraphs from the PDF into text files 
and ran wc over each meaningful chunk. The second column is the sum of the current and all previous sections. 
So we are comfortably away from the limit that even if some things might be counted 
slightly differently by eye in the administrative check.
```
6250 Max as per author guidelines 

213 213 Abstract
735 948 Intro 735 (478+257 Terminology)
806 1754 Values
243 1997 Competencies Intro
976 2973 Competencies Software/Tech
745 3718 Competencies Research
505 4223 Competencies Communication
664 4886 Specializations
380 5266 Future Work
328 5594 Conclusion
369 5963 Acknowledgements & References
201 6164 Biographies
```

**Comment by jpthiele** [comment]
And the slightly bad news:
I read on the [general overview ](https://www.computer.org/publications/author-resources) that an abstract should be between 100 and 200 words, we are 13 over....

And through removing the `\gls` we are left with the short codes as subsection headings in the competencies. Not sure if we want it like that.

**Comment by MakisH** [comment]
> And the slightly bad news: I read on the [general overview ](https://www.computer.org/publications/author-resources) that an abstract should be between 100 and 200 words, we are 13 over....

Slimmed it down to 200 by deleting mostly auxiliary words.

> And through removing the `\gls` we are left with the short codes as subsection headings in the competencies. Not sure if we want it like that.

Fixed that, thanks! I have not yet read through it, so there might be more such issues.

**Comment by MakisH** [comment]
> Currently we cite both the arXiv and F1000 version which brings us to 13 references. Additionally, all reference text will be counted for the overall word limit. I suggest we only reference F1000?

Removed the arxiv citation.

**Comment by jpthiele** [comment]
First of all, thank you Gerasimos!
Then I remembered something about natural persons as authors and re-checked with @sdruskat 
Yes, we need some and we would need someone who took part in the Dagstuhl seminar.
Therefore, the suggestion was to have Florian as first author, me as second and the project as third author.
@CaptainSifff I will start writing our biographies according to the [guidelines](https://www.computer.org/publications/author-resources) but some things you will have to write yourself, because I don't want to guess your research interests :)

**Comment by jpthiele** [comment]
And here is the updated tally (only recounting abstract and bios!).
This puts us slightly over which according to the author information will lead to a desk reject :/ 
And I am unsure whether or not they will count the title too... 

```
199 199 Abstract
735 934 Intro 735 (478+257 Terminology)
806 1740 Values
243 1983 Competencies Intro
976 2959 Competencies Software/Tech
745 3704 Competencies Research
505 4209 Competencies Communication
664 4873 Specializations
380 5253 Future Work
328 5581 Conclusion
369 5950 Acknowledgements & References
308 6258 Biographies
```

**Comment by jpthiele** [comment]
One quite natural shortening would be to agree on a subset of the specializations (maybe the currently most prevalent?)
and to add to the intro sentence about what the full paper provides.

**Comment by mhagdorn** [comment]
we could also drop the entire section and replace it with a list of specialisations that we have identified

**Comment by MakisH** [comment]
Most of the specializations are too short anyway. Let's just go with one paragraph listing all specializations and refer to the full paper. That would save us at least half a page.

I can do that tonight/tomorrow, unless someone else does it first.

**Comment by jpthiele** [comment]
I guess it would then fit best as a subsection of the competencies section, right?
And again, thank you Gerasimos!

**Comment by MakisH** [comment]
Made the section shorter, saving a lot and bringing the paper down to 8 pages total. Feel free to directly improve:

![Screenshot from 2024-12-11 19-57-23](https://github.com/user-attachments/assets/cc51b95b-8a12-4a5e-b78f-babc2f0e2e8d)

I had a quick read / sanity check, fixed some typos, and the body of the text looks good. Still missing:

- [ ] Elements in the biography of @CaptainSifff 
- [ ] Article type (editor task?)
- [ ] Publication name in the footer (editor or our task?)
- [ ] Header (editor task?)

**Comment by jpthiele** [comment]
Very good, I'm going to remove the `young` in teaching RSEs for various reasons.
I will also check tomorrow how much Metadata I can fill in from the special issue emails I got as Dagstuhl participant.

**Comment by mhagdorn** [comment]
excellent, the _young_ were on my list but I promptly forgot

**Comment by MakisH** [comment]
I actually got that from the [DORA declaration](https://sfdora.org/read/):

> The outputs from scientific research are many and varied, including: research articles reporting new knowledge, data, reagents, and software; intellectual property; and highly trained young scientists. 

But I agree it can go.

**Comment by jpthiele** [comment]
We are currently at 5771 words give or take, so a good and safe way away from the 6250 :partying_face:

**Comment by CaptainSifff** [comment]
I've added a small biography. and I've updated the online links to show the date of today.

**Comment by jpthiele** [comment]
I agree with Gerasimos and removed the dates.
I also slightly rearranged/shortened some sentences in the project biography, especially the last one.
Now we neatly fit on 8 pages.

**Comment by jpthiele** [comment]
If there are no objections by tomorrow evening ~18:00 CET I will hand in the paper to the special issue.

**Comment by mhagdorn** [comment]
I read through it again. The paper looks great now and we can be really pleased with it. Personally, I am very chuffed that the values got such a prominent part.

I have made some minor changes:
* on line 408: _research-wise_ to just _research_, research-wise sounds not quite right
* on line 617: replace _young_ with _budding_
* on line 646: just drop the word _young_
* on line 672: capitalised German Physical Society and Carpentries

I've really enjoyed collaborating on this paper with all of you.

**Comment by jpthiele** [comment]
```
Congratulations! Your Manuscript has been processed and submitted to the journal
```
I agree with Magnus, I enjoyed the collaboration too. 
And I really like how well the condensed version reads!

**Comment by MakisH** [comment]
I think that the condensed version is more inviting to read, and it was a nice learning experience how we could condense it. Let's set an upper page limit/target for the next one!

Great job, everyone!
